#!/bin/sh

set -e

PREREQ="plymouth"

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

#there is room for improvement
cp -a /usr/share/fonts/truetype/hack/Hack-Regular.ttf "${DESTDIR}/usr/share/fonts/truetype/hack/"